parameters:
  - name: noCache
    displayName: 'Build without cache'
    type: boolean
    default: false

trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

resources:
  pipelines:
    - pipeline: viseronModels
      source: "Viseron Models"
      trigger:
        branches:
          - dev
    - pipeline: viseronWheels
      source: "Viseron Wheels"
      trigger:
        branches:
          - dev
jobs:
  - template: templates/build.yaml
    parameters:
      image: base
      noCache: ${{ parameters.noCache }}

